### PR TITLE
Fix sequence numbers generation

### LINKED ISSUE #39: Invalid sequence number when `persist?` option is set to true.
When `Sink` `persist?` option is set to true then the `current_seq_num` of a track does not get incremented at all.

The code looks as follows:
```elixir
track = Map.update!(track, :current_seq_num, &(&1 + length(to_remove_segment_names)))
```
But the `to_remove_segment_names` is in this case empty therefore `:current_seq_num` stays forever a `0`.

[The invalid code fragment](https://github.com/membraneframework/membrane_http_adaptive_stream_plugin/blob/86f679eeb6dd1b75e8ea12311ef1c3d83569ffc9/lib/membrane_http_adaptive_stream/manifest/track.ex#L196)

### PR DESCRIPTION
**Pull request by Qizot**
Closes #39 

Additionally added `start_of_stream` notification to sink bin and prevented storing manifest with zero tracks.

### CODE REVIEW

File: lib/membrane_http_adaptive_stream/sink_bin.ex [hunk 1]
```diff
@@ -114,7 +114,10 @@ defmodule Membrane.HTTPAdaptiveStream.SinkBin do
     state = %{
       muxer_segment_duration: opts.muxer_segment_duration,
       mode: opts.hls_mode,
-      streams_counter: 0
+      streams_to_start: 0,
+      started?: false,
+      streams_to_end: 0,
+      ended?: false
```
Comment (daniel-jodlos) [inline lib/membrane_http_adaptive_stream/sink_bin.ex:120]: maybe `status: :awaiting_start | :playing | :ended` instead of `started?` and `ended?`?

File: lib/membrane_http_adaptive_stream/sink_bin.ex [hunk 2]
```diff
@@ -198,17 +207,33 @@ defmodule Membrane.HTTPAdaptiveStream.SinkBin do
...
+  end
+
+  @impl true
+  def handle_element_start_of_stream(_element, _ctx, state) do
     {:ok, state}
   end
 
+  def handle_element_end_of_stream({:sink, _}, _ctx, %{streams_to_end: 1, ended?: false} = state) do
+    {{:ok, notify: :end_of_stream}, %{state | streams_to_end: 0, ended?: true}}
+  end
```
Comment (daniel-jodlos) [inline lib/membrane_http_adaptive_stream/sink_bin.ex:230]: What `ended?: false` really gives us here? I think it will make sure that we don't send :end_of_stream twice, but I think it would be an expected behavior if someone connected a new pad after processing finished.

This obviously applies to `started?: false` as well

Comment (Qizot) [reply lib/membrane_http_adaptive_stream/sink_bin.ex:230]: Yup, forgot to change that after our internal discussion.

File: lib/membrane_http_adaptive_stream/sink_bin.ex (hunk 1 above)
Comment (Qizot) [reply lib/membrane_http_adaptive_stream/sink_bin.ex:120]: yup, much better

**Review by daniel-jodlos — APPROVED** [review]
